# Generated by Django 5.2.8 on 2025-11-11 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام شهر به فارسی', max_length=100, verbose_name='نام شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام دانشکده', max_length=200, unique=True, verbose_name='نام دانشکده')),
                ('code', models.CharField(help_text='کد منحصر به فرد دانشکده', max_length=20, unique=True, verbose_name='کد دانشکده')),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به دانشکده', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='آیا دانشکده فعال است؟', verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دانشکده',
                'verbose_name_plural': 'دانشکده\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نوع تماس (مثل تلفن ثابت، موبایل، ایمیل)', max_length=50, unique=True, verbose_name='نوع تماس')),
            ],
            options={
                'verbose_name': 'نوع تماس',
                'verbose_name_plural': 'انواع تماس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام کشور به فارسی', max_length=100, unique=True, verbose_name='نام کشور')),
                ('code', models.CharField(help_text='کد سه حرفی کشور (مثل IRN)', max_length=3, unique=True, verbose_name='کد کشور')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام درس', max_length=200, verbose_name='نام درس')),
                ('code', models.CharField(help_text='کد منحصر به فرد درس', max_length=20, verbose_name='کد درس')),
                ('credits', models.PositiveIntegerField(help_text='تعداد واحدهای درس', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='تعداد واحد')),
                ('course_type', models.CharField(help_text='نوع درس (اصلی، اختیاری، عمومی و ...)', max_length=50, verbose_name='نوع درس')),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به درس', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='آیا درس فعال است؟', verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
                'ordering': ['field_of_study', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام یا شماره اتاق', max_length=100, verbose_name='نام اتاق')),
                ('code', models.CharField(help_text='کد منحصر به فرد اتاق', max_length=20, unique=True, verbose_name='کد اتاق')),
                ('room_type', models.CharField(choices=[('C', 'کلاس'), ('L', 'آزمایشگاه'), ('O', 'سمینار'), ('A', 'آمفی\u200cتئاتر')], help_text='نوع اتاق', max_length=1, verbose_name='نوع اتاق')),
                ('capacity', models.PositiveIntegerField(help_text='ظرفیت اتاق', validators=[django.core.validators.MinValueValidator(1)], verbose_name='ظرفیت')),
                ('building', models.CharField(blank=True, help_text='نام ساختمان', max_length=100, null=True, verbose_name='ساختمان')),
                ('floor', models.IntegerField(blank=True, help_text='طبقه اتاق', null=True, verbose_name='طبقه')),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به اتاق', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='آیا اتاق فعال است؟', verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
                'ordering': ['building', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام ترم (مثل ترم اول ۱۴۰۳-۱۴۰۴)', max_length=100, verbose_name='نام ترم')),
                ('code', models.CharField(help_text='کد منحصر به فرد ترم', max_length=20, unique=True, verbose_name='کد ترم')),
                ('start_date', models.CharField(help_text='تاریخ شروع ترم به صورت شمسی', max_length=10, verbose_name='تاریخ شروع (شمسی)')),
                ('end_date', models.CharField(help_text='تاریخ پایان ترم به صورت شمسی', max_length=10, verbose_name='تاریخ پایان (شمسی)')),
                ('is_current', models.BooleanField(default=False, help_text='آیا این ترم جاری است؟', verbose_name='ترم جاری')),
                ('is_registration_open', models.BooleanField(default=False, help_text='آیا ثبت\u200cنام برای این ترم باز است؟', verbose_name='ثبت\u200cنام باز است')),
            ],
            options={
                'verbose_name': 'ترم',
                'verbose_name_plural': 'ترم\u200cها',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(help_text='کد منحصر به فرد کلاس', max_length=50, unique=True, verbose_name='کد کلاس')),
                ('day_of_week', models.CharField(choices=[('SA', 'شنبه'), ('SU', 'یکشنبه'), ('MO', 'دوشنبه'), ('TU', 'سه\u200cشنبه'), ('WE', 'چهارشنبه'), ('TH', 'پنج\u200cشنبه'), ('FR', 'جمعه')], help_text='روز هفته برگزاری کلاس', max_length=2, verbose_name='روز هفته')),
                ('start_time', models.TimeField(help_text='ساعت شروع کلاس', verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(help_text='ساعت پایان کلاس', verbose_name='ساعت پایان')),
                ('capacity', models.PositiveIntegerField(help_text='ظرفیت کلاس', validators=[django.core.validators.MinValueValidator(1)], verbose_name='ظرفیت')),
                ('is_active', models.BooleanField(default=True, help_text='آیا کلاس فعال است؟', verbose_name='فعال')),
                ('course', models.ForeignKey(help_text='درسی که این کلاس برای آن برگزار می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='EducationSystem.course', verbose_name='درس')),
                ('room', models.ForeignKey(blank=True, help_text='اتاقی که کلاس در آن برگزار می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='EducationSystem.room', verbose_name='اتاق')),
                ('term', models.ForeignKey(help_text='ترمی که این کلاس در آن برگزار می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='EducationSystem.term', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['term', 'course', 'class_code'],
                'unique_together': {('class_code', 'term')},
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام رشته تحصیلی', max_length=200, verbose_name='نام رشته')),
                ('code', models.CharField(help_text='کد منحصر به فرد رشته', max_length=20, verbose_name='کد رشته')),
                ('degree_level', models.CharField(help_text='مقطع تحصیلی (کارشناسی، کارشناسی ارشد، دکتری و ...)', max_length=50, verbose_name='مقطع تحصیلی')),
                ('total_credits', models.PositiveIntegerField(help_text='تعداد واحدهای مورد نیاز برای فارغ\u200cالتحصیلی', verbose_name='تعداد واحد کل')),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به رشته', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='آیا رشته فعال است؟', verbose_name='فعال')),
                ('college', models.ForeignKey(help_text='دانشکده مربوط به این رشته', on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_study', to='EducationSystem.college', verbose_name='دانشکده')),
            ],
            options={
                'verbose_name': 'رشته تحصیلی',
                'verbose_name_plural': 'رشته\u200cهای تحصیلی',
                'ordering': ['college', 'name'],
                'unique_together': {('code', 'college')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='field_of_study',
            field=models.ForeignKey(help_text='رشته مربوط به این درس', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='EducationSystem.fieldofstudy', verbose_name='رشته'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='نام فرد', max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(help_text='نام خانوادگی فرد', max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(help_text='کد ملی ۱۰ رقمی', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً ۱۰ رقم باشد', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('id_number', models.CharField(help_text='شماره شناسنامه', max_length=20, unique=True, verbose_name='شماره شناسنامه')),
                ('birth_date_shamsi', models.CharField(help_text='تاریخ تولد به صورت شمسی (YYYY/MM/DD)', max_length=10, verbose_name='تاریخ تولد (شمسی)')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], help_text='جنسیت فرد', max_length=1, verbose_name='جنسیت')),
                ('marital_status', models.CharField(choices=[('S', 'مجرد'), ('M', 'متاهل'), ('D', 'مطلقه'), ('W', 'بیوه')], help_text='وضعیت تاهل فرد', max_length=1, verbose_name='وضعیت تاهل')),
                ('military_status', models.CharField(blank=True, choices=[('E', 'معاف'), ('C', 'مشمول'), ('D', 'دارای کارت پایان خدمت'), ('N', 'غیرمشمول')], help_text='وضعیت نظام وظیفه (فقط برای آقایان)', max_length=1, null=True, verbose_name='وضعیت نظام وظیفه')),
                ('address', models.TextField(blank=True, help_text='آدرس کامل محل سکونت', null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد', verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین بروزرسانی', verbose_name='تاریخ بروزرسانی')),
                ('professor_code', models.CharField(help_text='کد منحصر به فرد استاد', max_length=20, unique=True, verbose_name='کد استادی')),
                ('employee_number', models.CharField(blank=True, help_text='شماره پرسنلی استاد', max_length=20, null=True, unique=True, verbose_name='شماره پرسنلی')),
                ('contract_type', models.CharField(choices=[('F', 'تمام وقت'), ('P', 'پاره وقت'), ('V', 'مهمان')], help_text='نوع قرارداد استخدامی', max_length=1, verbose_name='نوع قرارداد')),
                ('hire_date', models.CharField(help_text='تاریخ شروع به کار به صورت شمسی', max_length=10, verbose_name='تاریخ استخدام (شمسی)')),
                ('expertise', models.TextField(blank=True, help_text='حوزه\u200cهای تخصصی استاد', null=True, verbose_name='تخصص')),
                ('is_active', models.BooleanField(default=True, help_text='آیا استاد فعال است؟', verbose_name='فعال')),
                ('birth_place', models.ForeignKey(blank=True, help_text='شهر محل تولد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_born_people', related_query_name='%(class)s_born', to='EducationSystem.city', verbose_name='محل تولد')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
                'ordering': ['professor_code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام استان به فارسی', max_length=100, unique=True, verbose_name='نام استان')),
                ('country', models.ForeignKey(help_text='کشوری که این استان به آن تعلق دارد', on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='EducationSystem.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(help_text='استانی که این شهر به آن تعلق دارد', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='EducationSystem.province', verbose_name='استان'),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام گرایش تحصیلی', max_length=200, verbose_name='نام گرایش')),
                ('code', models.CharField(help_text='کد منحصر به فرد گرایش', max_length=20, verbose_name='کد گرایش')),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به گرایش', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='آیا گرایش فعال است؟', verbose_name='فعال')),
                ('field_of_study', models.ForeignKey(help_text='رشته مربوط به این گرایش', on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='EducationSystem.fieldofstudy', verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'گرایش',
                'verbose_name_plural': 'گرایش\u200cها',
                'ordering': ['field_of_study', 'name'],
                'unique_together': {('code', 'field_of_study')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='نام فرد', max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(help_text='نام خانوادگی فرد', max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(help_text='کد ملی ۱۰ رقمی', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً ۱۰ رقم باشد', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('id_number', models.CharField(help_text='شماره شناسنامه', max_length=20, unique=True, verbose_name='شماره شناسنامه')),
                ('birth_date_shamsi', models.CharField(help_text='تاریخ تولد به صورت شمسی (YYYY/MM/DD)', max_length=10, verbose_name='تاریخ تولد (شمسی)')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], help_text='جنسیت فرد', max_length=1, verbose_name='جنسیت')),
                ('marital_status', models.CharField(choices=[('S', 'مجرد'), ('M', 'متاهل'), ('D', 'مطلقه'), ('W', 'بیوه')], help_text='وضعیت تاهل فرد', max_length=1, verbose_name='وضعیت تاهل')),
                ('military_status', models.CharField(blank=True, choices=[('E', 'معاف'), ('C', 'مشمول'), ('D', 'دارای کارت پایان خدمت'), ('N', 'غیرمشمول')], help_text='وضعیت نظام وظیفه (فقط برای آقایان)', max_length=1, null=True, verbose_name='وضعیت نظام وظیفه')),
                ('address', models.TextField(blank=True, help_text='آدرس کامل محل سکونت', null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد', verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین بروزرسانی', verbose_name='تاریخ بروزرسانی')),
                ('employee_number', models.CharField(help_text='شماره پرسنلی کارمند', max_length=20, unique=True, verbose_name='شماره پرسنلی')),
                ('contract_type', models.CharField(choices=[('F', 'تمام وقت'), ('P', 'پاره وقت'), ('C', 'قراردادی')], help_text='نوع قرارداد استخدامی', max_length=1, verbose_name='نوع قرارداد')),
                ('hire_date', models.CharField(help_text='تاریخ شروع به کار به صورت شمسی', max_length=10, verbose_name='تاریخ استخدام (شمسی)')),
                ('position', models.CharField(help_text='سمت شغلی کارمند', max_length=100, verbose_name='سمت')),
                ('is_active', models.BooleanField(default=True, help_text='آیا کارمند فعال است؟', verbose_name='فعال')),
                ('birth_place', models.ForeignKey(blank=True, help_text='شهر محل تولد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_born_people', related_query_name='%(class)s_born', to='EducationSystem.city', verbose_name='محل تولد')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='نام فرد', max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(help_text='نام خانوادگی فرد', max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(help_text='کد ملی ۱۰ رقمی', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً ۱۰ رقم باشد', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('id_number', models.CharField(help_text='شماره شناسنامه', max_length=20, unique=True, verbose_name='شماره شناسنامه')),
                ('birth_date_shamsi', models.CharField(help_text='تاریخ تولد به صورت شمسی (YYYY/MM/DD)', max_length=10, verbose_name='تاریخ تولد (شمسی)')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], help_text='جنسیت فرد', max_length=1, verbose_name='جنسیت')),
                ('marital_status', models.CharField(choices=[('S', 'مجرد'), ('M', 'متاهل'), ('D', 'مطلقه'), ('W', 'بیوه')], help_text='وضعیت تاهل فرد', max_length=1, verbose_name='وضعیت تاهل')),
                ('military_status', models.CharField(blank=True, choices=[('E', 'معاف'), ('C', 'مشمول'), ('D', 'دارای کارت پایان خدمت'), ('N', 'غیرمشمول')], help_text='وضعیت نظام وظیفه (فقط برای آقایان)', max_length=1, null=True, verbose_name='وضعیت نظام وظیفه')),
                ('address', models.TextField(blank=True, help_text='آدرس کامل محل سکونت', null=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد', verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین بروزرسانی', verbose_name='تاریخ بروزرسانی')),
                ('student_number', models.CharField(help_text='شماره دانشجویی منحصر به فرد', max_length=20, unique=True, verbose_name='شماره دانشجویی')),
                ('enrollment_date', models.CharField(help_text='تاریخ ثبت\u200cنام در دانشگاه به صورت شمسی', max_length=10, verbose_name='تاریخ ثبت\u200cنام (شمسی)')),
                ('is_active', models.BooleanField(default=True, help_text='آیا دانشجو فعال است؟', verbose_name='فعال')),
                ('birth_place', models.ForeignKey(blank=True, help_text='شهر محل تولد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_born_people', related_query_name='%(class)s_born', to='EducationSystem.city', verbose_name='محل تولد')),
                ('field_of_study', models.ForeignKey(blank=True, help_text='رشته تحصیلی دانشجو', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='EducationSystem.fieldofstudy', verbose_name='رشته تحصیلی')),
                ('specialization', models.ForeignKey(blank=True, help_text='گرایش تحصیلی دانشجو', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='EducationSystem.specialization', verbose_name='گرایش')),
            ],
            options={
                'verbose_name': 'دانشجو',
                'verbose_name_plural': 'دانشجویان',
                'ordering': ['student_number'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='شناسه شی مورد نظر', verbose_name='شناسه شی')),
                ('value', models.CharField(help_text='مقدار تماس (شماره تلفن، آدرس ایمیل و ...)', max_length=255, verbose_name='مقدار')),
                ('is_primary', models.BooleanField(default=False, help_text='آیا این تماس اصلی است؟', verbose_name='تماس اصلی')),
                ('content_type', models.ForeignKey(help_text='نوع مدلی که این تماس به آن تعلق دارد', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('contact_type', models.ForeignKey(help_text='نوع تماس (تلفن، موبایل، ایمیل و ...)', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='EducationSystem.contacttype', verbose_name='نوع تماس')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس\u200cها',
                'ordering': ['-is_primary', 'contact_type'],
                'unique_together': {('content_type', 'object_id', 'contact_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='CourseCorequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True, help_text='آیا این هم\u200cنیاز اجباری است؟', verbose_name='اجباری')),
                ('corequisite_course', models.ForeignKey(help_text='درسی که باید همزمان با این درس اخذ شود', on_delete=django.db.models.deletion.CASCADE, related_name='corequired_with', to='EducationSystem.course', verbose_name='هم\u200cنیاز')),
                ('course', models.ForeignKey(help_text='درسی که هم\u200cنیاز دارد', on_delete=django.db.models.deletion.CASCADE, related_name='corequisites', to='EducationSystem.course', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'هم\u200cنیاز درس',
                'verbose_name_plural': 'هم\u200cنیازهای دروس',
                'unique_together': {('course', 'corequisite_course')},
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True, help_text='آیا این پیش\u200cنیاز اجباری است؟', verbose_name='اجباری')),
                ('course', models.ForeignKey(help_text='درسی که پیش\u200cنیاز دارد', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='EducationSystem.course', verbose_name='درس')),
                ('prerequisite_course', models.ForeignKey(help_text='درسی که باید قبل از این درس گذرانده شود', on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='EducationSystem.course', verbose_name='پیش\u200cنیاز')),
            ],
            options={
                'verbose_name': 'پیش\u200cنیاز درس',
                'verbose_name_plural': 'پیش\u200cنیازهای دروس',
                'unique_together': {('course', 'prerequisite_course')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'field_of_study')},
        ),
        migrations.CreateModel(
            name='ProfessorCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان تخصیص استاد به کلاس', verbose_name='تاریخ تخصیص')),
                ('is_primary', models.BooleanField(default=True, help_text='آیا این استاد استاد اصلی کلاس است؟', verbose_name='استاد اصلی')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی', null=True, verbose_name='یادداشت')),
                ('class_course', models.ForeignKey(help_text='کلاسی که استاد آن را تدریس می\u200cکند', on_delete=django.db.models.deletion.CASCADE, related_name='professor_assignments', to='EducationSystem.class', verbose_name='کلاس')),
                ('professor', models.ForeignKey(help_text='استادی که درس را تدریس می\u200cکند', on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='EducationSystem.professor', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'تخصیص استاد به کلاس',
                'verbose_name_plural': 'تخصیص\u200cهای اساتید',
                'ordering': ['-assignment_date'],
                'unique_together': {('professor', 'class_course')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'province')},
        ),
        migrations.CreateModel(
            name='ProfessorSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_quality', models.IntegerField(choices=[(1, 'خیلی ضعیف'), (2, 'ضعیف'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], help_text='رتبه کیفیت تدریس استاد', verbose_name='کیفیت تدریس')),
                ('communication', models.IntegerField(choices=[(1, 'خیلی ضعیف'), (2, 'ضعیف'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], help_text='رتبه ارتباط استاد با دانشجویان', verbose_name='ارتباط')),
                ('punctuality', models.IntegerField(choices=[(1, 'خیلی ضعیف'), (2, 'ضعیف'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], help_text='رتبه انضباط زمانی استاد', verbose_name='انضباط زمانی')),
                ('overall_rating', models.IntegerField(choices=[(1, 'خیلی ضعیف'), (2, 'ضعیف'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], help_text='امتیاز کلی استاد', verbose_name='امتیاز کلی')),
                ('comments', models.TextField(blank=True, help_text='نظرات و پیشنهادات دانشجو', null=True, verbose_name='نظرات')),
                ('survey_date', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان تکمیل نظرسنجی', verbose_name='تاریخ نظرسنجی')),
                ('class_course', models.ForeignKey(help_text='کلاسی که نظرسنجی برای آن انجام شده', on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='EducationSystem.class', verbose_name='کلاس')),
                ('professor', models.ForeignKey(help_text='استادی که درباره او نظرسنجی شده', on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='EducationSystem.professor', verbose_name='استاد')),
                ('student', models.ForeignKey(help_text='دانشجویی که نظرسنجی را تکمیل کرده', on_delete=django.db.models.deletion.CASCADE, related_name='professor_surveys', to='EducationSystem.student', verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'نظرسنجی استاد',
                'verbose_name_plural': 'نظرسنجی\u200cهای اساتید',
                'ordering': ['-survey_date'],
                'unique_together': {('student', 'professor', 'class_course')},
            },
        ),
        migrations.CreateModel(
            name='StudentClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ثبت\u200cنام', verbose_name='تاریخ ثبت\u200cنام')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, help_text='نمره دانشجو در این کلاس', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره')),
                ('status', models.CharField(choices=[('R', 'ثبت\u200cنام شده'), ('P', 'قبول'), ('F', 'مردود'), ('W', 'حذف'), ('I', 'ناقص')], default='R', help_text='وضعیت ثبت\u200cنام و نمره دانشجو', max_length=1, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی', null=True, verbose_name='یادداشت')),
                ('class_course', models.ForeignKey(help_text='کلاسی که دانشجو در آن ثبت\u200cنام کرده', on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='EducationSystem.class', verbose_name='کلاس')),
                ('student', models.ForeignKey(help_text='دانشجویی که در کلاس ثبت\u200cنام کرده', on_delete=django.db.models.deletion.CASCADE, related_name='class_registrations', to='EducationSystem.student', verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام دانشجو در کلاس',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای دانشجویان',
                'ordering': ['-registration_date'],
                'unique_together': {('student', 'class_course')},
            },
        ),
    ]
