# Generated by Django 5.2.8 on 2025-11-18 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='روش ثبت حضور (QR، NFC، دستی)', max_length=50, unique=True, verbose_name='روش ثبت حضور')),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به روش ثبت حضور', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این روش فعال است؟', verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'روش ثبت حضور',
                'verbose_name_plural': 'روش\u200cهای ثبت حضور',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='روش پرداخت (درگاه بانکی، کیف پول، وام)', max_length=50, unique=True, verbose_name='روش پرداخت')),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به روش پرداخت', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این روش فعال است؟', verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='وضعیت پرداخت (موفق، ناموفق، در حال پردازش)', max_length=50, unique=True, verbose_name='وضعیت پرداخت')),
                ('description', models.TextField(blank=True, help_text='توضیحات مربوط به وضعیت پرداخت', null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'وضعیت پرداخت',
                'verbose_name_plural': 'وضعیت\u200cهای پرداخت',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('A', 'فعال'), ('G', 'فارغ\u200cالتحصیل'), ('W', 'انصراف\u200cداده'), ('S', 'معلق')], default='A', help_text='وضعیت تحصیلی دانشجو (فعال، فارغ\u200cالتحصیل، انصراف\u200cداده)', max_length=1, verbose_name='وضعیت تحصیلی'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='آدرس ایمیل دانشجو (example@domain.com)', max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, help_text='تاریخ ثبت\u200cنام در دانشگاه (مقدار پیش\u200cفرض = زمان فعلی)', verbose_name='تاریخ ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(help_text='شماره دانشجویی منحصر به فرد - باید بزرگتر از 0 باشد', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='شماره دانشجویی باید فقط شامل اعداد باشد', regex='^\\d+$')], verbose_name='شماره دانشجویی'),
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='مبلغ پرداختی (تومان)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان پرداخت (مقدار پیش\u200cفرض = زمان فعلی)', verbose_name='تاریخ پرداخت')),
                ('transaction_code', models.CharField(help_text='کد منحصر به فرد تراکنش (مثل PAY202510190001)', max_length=50, unique=True, verbose_name='کد تراکنش')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی', null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد', verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین بروزرسانی', verbose_name='تاریخ بروزرسانی')),
                ('payment_method', models.ForeignKey(blank=True, help_text='روش پرداخت (درگاه بانکی، کیف پول، وام)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='EducationSystem.paymentmethod', verbose_name='روش پرداخت')),
                ('payment_status', models.ForeignKey(blank=True, help_text='وضعیت پرداخت (موفق، ناموفق، در حال پردازش)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='EducationSystem.paymentstatus', verbose_name='وضعیت پرداخت')),
                ('student', models.ForeignKey(help_text='دانشجویی که شهریه پرداخت کرده', on_delete=django.db.models.deletion.CASCADE, related_name='tuition_payments', to='EducationSystem.student', verbose_name='دانشجو')),
                ('term', models.ForeignKey(blank=True, help_text='ترمی که این پرداخت برای آن است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_payments', to='EducationSystem.term', verbose_name='ترم')),
            ],
            options={
                'verbose_name': 'پرداخت شهریه',
                'verbose_name_plural': 'پرداخت\u200cهای شهریه',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_time', models.DateTimeField(help_text='تاریخ و زمان دقیق حضور دانشجو', verbose_name='زمان حضور')),
                ('is_approved_by_professor', models.BooleanField(default=False, help_text='آیا حضور توسط استاد تایید شده است؟', verbose_name='تایید استاد')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای اضافی', null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ثبت رکورد', verbose_name='تاریخ ثبت')),
                ('attendance_method', models.ForeignKey(blank=True, help_text='روش ثبت حضور (QR، NFC، دستی)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='EducationSystem.attendancemethod', verbose_name='روش ثبت حضور')),
                ('class_course', models.ForeignKey(help_text='کلاسی که حضور در آن ثبت می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='EducationSystem.class', verbose_name='کلاس')),
                ('student', models.ForeignKey(help_text='دانشجویی که حضور او ثبت می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='EducationSystem.student', verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'حضور در کلاس',
                'verbose_name_plural': 'حضور و غیاب کلاس\u200cها',
                'ordering': ['-attendance_time'],
                'unique_together': {('student', 'class_course', 'attendance_time')},
            },
        ),
    ]
